-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin
(
    contact_no character varying(20) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.demo
(
    userid integer NOT NULL DEFAULT nextval('demo_userid_seq'::regclass),
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    userrole character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT demo_pkey PRIMARY KEY (userid)
);

CREATE TABLE IF NOT EXISTS public.organisation
(
    organisation_id integer NOT NULL DEFAULT nextval('organisation_organisation_id_seq'::regclass),
    organisation_name character varying(255) COLLATE pg_catalog."default",
    organisation_address character varying(255) COLLATE pg_catalog."default",
    organisation_contact character varying(255) COLLATE pg_catalog."default",
    organisation_email character varying(255) COLLATE pg_catalog."default",
    organisation_type character varying(255) COLLATE pg_catalog."default",
    organisation_activities text COLLATE pg_catalog."default",
    organisation_legal_status_document bytea,
    coordinator_name character varying(255) COLLATE pg_catalog."default",
    coordinator_email character varying(255) COLLATE pg_catalog."default",
    organisation_created_at timestamp without time zone DEFAULT now(),
    organisation_updated_at timestamp without time zone,
    CONSTRAINT organisation_pkey PRIMARY KEY (organisation_id)
);

CREATE TABLE IF NOT EXISTS public.part
(
    participant_id integer NOT NULL DEFAULT nextval('participants_participant_id_seq'::regclass),
    participant_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    participant_email character varying(255) COLLATE pg_catalog."default",
    participant_contact character varying(20) COLLATE pg_catalog."default",
    participant_address text COLLATE pg_catalog."default",
    participant_age character varying(10) COLLATE pg_catalog."default",
    participant_gender character varying(255) COLLATE pg_catalog."default",
    training_location_id integer,
    participant_created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    participant_updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    participant_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'new'::character varying,
    participant_created_date timestamp without time zone,
    participant_updated_date timestamp without time zone,
    participant_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT part_pkey PRIMARY KEY (participant_id)
);

CREATE TABLE IF NOT EXISTS public.participants
(
    participant_id integer NOT NULL DEFAULT nextval('participants_participant_id_seq'::regclass),
    participant_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    participant_email character varying(255) COLLATE pg_catalog."default",
    participant_contact character varying(20) COLLATE pg_catalog."default",
    participant_address text COLLATE pg_catalog."default",
    participant_age character varying(10) COLLATE pg_catalog."default",
    participant_gender character varying(255) COLLATE pg_catalog."default",
    training_location_id integer,
    participant_created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    participant_updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    participant_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'new'::character varying,
    participant_created_date timestamp without time zone,
    participant_updated_date timestamp without time zone,
    participant_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT participants_pkey PRIMARY KEY (participant_id)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id integer NOT NULL DEFAULT nextval('sessions_id_seq'::regclass),
    trainer_id integer,
    participant_id integer,
    scheduled_datetime timestamp without time zone,
    actual_datetime timestamp without time zone,
    hours_trained double precision,
    picture_path text COLLATE pg_catalog."default",
    video_path text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    session_current_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    session_update_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    session_status character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'NEW'::character varying,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.trainer
(
    trainer_id integer NOT NULL DEFAULT nextval('trainer_trainer_id_seq'::regclass),
    trainer_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    trainer_email character varying(255) COLLATE pg_catalog."default",
    trainer_contact character varying(255) COLLATE pg_catalog."default",
    trainer_address text COLLATE pg_catalog."default",
    trainer_age interval,
    trainer_gender character varying(255) COLLATE pg_catalog."default",
    trainer_education character varying(255) COLLATE pg_catalog."default",
    trainer_aadhar_no character varying(255) COLLATE pg_catalog."default",
    trainer_created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    trainer_updated_at timestamp without time zone,
    trainer_training_completion_date date NOT NULL,
    training_location_id integer,
    organisation_id integer,
    trainer_language text[] COLLATE pg_catalog."default",
    trainer_status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'NOT CERTIFIED'::character varying,
    trainer_code character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PST2023X'::character varying,
    CONSTRAINT trainer_pkey PRIMARY KEY (trainer_id)
);

CREATE TABLE IF NOT EXISTS public.trainers_availability
(
    trainer_id integer,
    blocked_date date,
    availability_time_range tsrange
);

CREATE TABLE IF NOT EXISTS public.training_locations_list
(
    training_location_id integer NOT NULL,
    training_location character varying(255) COLLATE pg_catalog."default",
    training_location_address character varying(255) COLLATE pg_catalog."default",
    training_location_latitude double precision,
    training_location_longitude double precision,
    training_location_created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    training_location_updated timestamp without time zone,
    training_location_picture text COLLATE pg_catalog."default",
    CONSTRAINT training_locations_list_pkey PRIMARY KEY (training_location_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    email text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.users_signup
(
    user_id integer NOT NULL DEFAULT nextval('users_signup_user_id_seq'::regclass),
    contact_no character varying COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    role character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_signup_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_signup_contact_no_key UNIQUE (contact_no)
);

ALTER TABLE IF EXISTS public.trainers_availability
    ADD CONSTRAINT trainers_availability_trainer_id_fkey FOREIGN KEY (trainer_id)
    REFERENCES public.trainer (trainer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;